version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /packaging/quotes
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /packaging/desk
    schedule:
      interval: weekly
