name: Desk

on:
  pull_request:

permissions:
  contents: read

jobs:
  desk:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Scala CLI
        uses: VirtusLab/scala-cli-setup@v1.16.0
        with:
          scala-cli-version: "1.16.0"

      - name: Check formatting
        run: scala-cli fmt --check .

      - name: Run tests
        run: scala-cli test . --test-only 'day26.ExercisesDay26Suite'
